### ISSUE TITLE
fastbow on 4 enchants

### ISSUE THREAD

**Issue by yellow-pillow** [Auxilor/EcoEnchants#146]
**Describe the bug**
buckshot, tripleshot, succession and pentashot  - enchantments for which the player who shoots gets kicked

**To Reproduce**
just shoot a bow with any of these enchantments and you will be kicked (if you shoot with full tension it will happen in 2-3 shots)

**Screenshots**
![image](https://user-images.githubusercontent.com/90108493/153296833-88261c05-36d9-41e0-8938-ef9f9fccb7f6.png)

**Server Information (please complete the following information):**
- Version: 
![image](https://user-images.githubusercontent.com/90108493/153277345-ea73a69f-ff38-49df-8740-a7212c4164c6.png)

- Version of plugin and eco
![image](https://user-images.githubusercontent.com/90108493/153277469-fa6c3e17-9b4b-4d75-a949-70f1d1557a51.png)
![image](https://user-images.githubusercontent.com/90108493/153277523-c81b62da-e3de-424e-9097-0878609e8d79.png)

**Comment by WillFP** [comment]
Fixed in latest

**Comment by kforbro** [comment]
![image](https://user-images.githubusercontent.com/39985355/177292360-206abbe9-4d82-4d4f-b81f-ad9237f6da51.png)
![image](https://user-images.githubusercontent.com/39985355/177292427-531e3808-d91c-4601-980c-7ccce4d8f216.png)
not fixed
